# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u23bK-rwmJMaj0bCHMuPNYxVrFk-QTuN
"""

import numpy as np
from scipy import special
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from dataclasses import dataclass, field
from typing import List, Dict, Tuple, Optional
import time
import os
import sys
import copy

SEED = 42
np.random.seed(SEED)

OUT_FIG = "figures"
OUT_RES = "results"
os.makedirs(OUT_FIG, exist_ok=True)
os.makedirs(OUT_RES, exist_ok=True)

try:
    sys.stdout.reconfigure(line_buffering=True)
except Exception:
    pass


@dataclass
class SystemConfig:
    K_flows: int = 12
    class_mix: Tuple[float, float, float] = (0.34, 0.33, 0.33)

    period_TT: float = 2e-3
    period_AVB: float = 4e-3
    period_BE: float = 8e-3
    deadline_TT: float = 2.0e-3
    deadline_AVB: float = 4.0e-3
    deadline_BE: float = 8.0e-3
    size_TT: int = 256
    size_AVB: int = 512
    size_BE: int = 1024
    reliability_TT: float = 1 - 1e-6
    reliability_AVB: float = 1 - 1e-4
    reliability_BE: float = 1 - 1e-2
    hyperperiod: float = 8e-3

    R_TSN: float = 100e9
    hops_short: int = 2
    hops_long: int = 4

    bandwidth_total: float = 80e6
    n0_density: float = -174.0
    gamma_star_dB: float = 6.0
    slot_len: float = 25e-6
    retx_delay: float = 100e-6
    p_max: float = 3.0
    interference_floor: float = 1e-13

    area_radius: float = 60.0
    C_const_dB: float = 35.7
    d0: float = 5.0
    d1: float = 25.0
    shadowing_std_dB: float = 6.0

    alpha1: float = 30.0
    alpha2: float = 12.0
    alpha3: float = 25.0
    alpha4: float = 0.01
    beta_retx: float = 1.0
    w_class: Dict[str, float] = field(default_factory=lambda: {"TT": 3.0, "AVB": 1.5, "BE": 0.5})
    wj_class: Dict[str, float] = field(default_factory=lambda: {"TT": 1.5, "AVB": 0.7, "BE": 0.2})

    N_max: int = 6
    retx_safety_margin: float = 2.5

    hidden_dim: int = 256
    gamma_discount: float = 0.95
    gae_lambda: float = 0.9
    clip_eps: float = 0.2
    lr: float = 3e-4
    entropy_coef_start: float = 0.01
    entropy_coef_end: float = 0.001
    train_episodes_stage: int = 1200
    steps_per_episode: int = 120
    minibatch_epochs: int = 4
    batch_size: int = 512
    max_K: int = 24
    random_seed: int = SEED

    @property
    def n0_linear(self) -> float:
        return 10 ** (self.n0_density / 10) / 1000.0

    @property
    def gamma_star(self) -> float:
        return 10 ** (self.gamma_star_dB / 10)


CLASSES = ["TT", "AVB", "BE"]
PLOT_METHODS = ["Proposed", "MAPPO-M", "Random"]


def generate_flows(cfg: SystemConfig, K: int, rng: np.random.RandomState) -> List[Dict]:
    counts = np.round(np.array(cfg.class_mix) * K).astype(int)
    counts[-1] = K - counts[:-1].sum()
    labels = []
    for c, n in zip(CLASSES, counts):
        labels += [c] * n
    rng.shuffle(labels)
    flows = []
    for k, c in enumerate(labels):
        if c == "TT":
            T, D, rho, rel = cfg.period_TT, cfg.deadline_TT, cfg.size_TT, cfg.reliability_TT
        elif c == "AVB":
            T, D, rho, rel = cfg.period_AVB, cfg.deadline_AVB, cfg.size_AVB, cfg.reliability_AVB
        else:
            T, D, rho, rel = cfg.period_BE, cfg.deadline_BE, cfg.size_BE, cfg.reliability_BE
        n_frames = max(1, int(round(cfg.hyperperiod / T)))
        flows.append(dict(id=k, cls=c, T=T, D=D, rho=rho * 8, eps=1 - rel, n_frames=n_frames))
    return flows


class Channel:
    def __init__(self, cfg: SystemConfig, K: int, rng: np.random.RandomState):
        self.cfg = cfg
        self.K = K
        self.rng = rng
        self.positions = None
        self.lam = None
        self.reset()

    def reset(self):
        cfg = self.cfg
        ang = self.rng.uniform(0, 2 * np.pi, self.K)
        r = np.sqrt(self.rng.uniform(0, 1, self.K)) * cfg.area_radius
        self.positions = np.column_stack([r * np.cos(ang), r * np.sin(ang)])
        self._refresh_large_scale()

    def _refresh_large_scale(self):
        cfg = self.cfg
        d = np.linalg.norm(self.positions, axis=1)
        d = np.clip(d, 0.5, None)
        PL = np.zeros_like(d)
        for i, di in enumerate(d):
            if di > cfg.d1:
                PL[i] = -cfg.C_const_dB - 35 * np.log10(di)
            elif di > cfg.d0:
                PL[i] = -cfg.C_const_dB - 15 * np.log10(cfg.d1) - 20 * np.log10(di)
            else:
                PL[i] = -cfg.C_const_dB - 15 * np.log10(cfg.d1) - 20 * np.log10(cfg.d0)
        SH = self.rng.normal(0, cfg.shadowing_std_dB, self.K)
        self.lam = 10 ** (PL / 10) * 10 ** (SH / 10)

    def sample_attempt_gain(self) -> np.ndarray:
        return self.rng.exponential(1.0, size=self.K)


def wired_latency(cfg: SystemConfig, route: np.ndarray, rho: np.ndarray,
                  gate_priority: np.ndarray) -> np.ndarray:
    hops = np.where(route == 0, cfg.hops_short, cfg.hops_long)
    base = hops * rho / cfg.R_TSN
    K = len(rho)
    queue = np.zeros(K)
    for k in range(K):
        ahead = (gate_priority > gate_priority[k]) & (route == route[k])
        queue[k] = rho[ahead].sum() / cfg.R_TSN
    return base + queue


def wireless_latency_and_failure(cfg: SystemConfig, channel: Channel, rho: np.ndarray,
                                 power: np.ndarray, retx_budget: np.ndarray,
                                 order_rank: np.ndarray, airtime_norm: np.ndarray,
                                 rng: np.random.RandomState) -> Tuple[np.ndarray, np.ndarray]:
    K = len(rho)
    B_k = cfg.bandwidth_total / K
    n0 = cfg.n0_linear
    denom = B_k * n0 + cfg.interference_floor

    max_budget = int(retx_budget.max()) if K > 0 else 0
    cum_gain = np.zeros(K)
    attempts_used = np.ones(K, dtype=int)
    success = np.zeros(K, dtype=bool)
    for attempt in range(1, max_budget + 2):
        still_trying = (~success) & (attempt <= retx_budget + 1)
        if not still_trying.any():
            break
        g_i = channel.sample_attempt_gain()
        cum_gain = np.where(still_trying, cum_gain + g_i, cum_gain)
        attempts_used = np.where(still_trying, attempt, attempts_used)
        snr_now = power * channel.lam * np.maximum(cum_gain, 1e-30) / denom
        newly_ok = still_trying & (snr_now >= cfg.gamma_star)
        success = success | newly_ok
    snr_final = power * channel.lam * np.maximum(cum_gain, 1e-30) / denom
    rate = B_k * np.log2(1 + np.maximum(snr_final, 1e-12))
    tx_time = np.ceil((rho / np.maximum(rate, 1.0)) / cfg.slot_len) * cfg.slot_len
    tx_time = np.minimum(tx_time, 0.5)
    extra_retx = np.maximum(attempts_used - 1, 0)
    retx_time = extra_retx * cfg.retx_delay

    n_t = int((airtime_norm > 1e-3).sum())
    n_t = max(n_t, 1)
    contend_global = (n_t - 1) * 0.5 * cfg.slot_len
    L_air = tx_time + retx_time + contend_global

    total_attempts = retx_budget + 1
    threshold = cfg.gamma_star * denom / np.maximum(power * channel.lam, 1e-30)
    fail_prob = special.gammainc(total_attempts, threshold)
    fail_prob = np.clip(fail_prob, 0.0, 1.0)
    return L_air, fail_prob


def evaluate_schedule(cfg: SystemConfig, flows: List[Dict], channel: Channel,
                      route_prob: np.ndarray, gate_priority: np.ndarray,
                      airtime_frac: np.ndarray, order_raw: np.ndarray,
                      power_frac: np.ndarray, retx_frac: np.ndarray,
                      rng: np.random.RandomState) -> Dict:
    K = len(flows)
    rho = np.array([f["rho"] for f in flows], dtype=float)
    D = np.array([f["D"] for f in flows])
    eps_req = np.array([f["eps"] for f in flows])
    n_frames = np.array([f["n_frames"] for f in flows])
    cls = np.array([f["cls"] for f in flows])

    route = (route_prob > 0.5).astype(int)
    L_w = wired_latency(cfg, route, rho, gate_priority)
    slack = np.maximum(0.0, D - L_w) * cfg.retx_safety_margin + 1e-9

    airtime_raw = np.clip(airtime_frac, 1e-3, 1.0)
    denom_a = airtime_raw.sum()
    airtime_norm = airtime_raw / denom_a if denom_a > 1.0 else airtime_raw
    order_rank = (-order_raw).argsort().argsort().astype(float)

    power_raw = np.clip(power_frac, 1e-3, 1.0)
    power = power_raw / power_raw.sum() * cfg.p_max

    Nmax_feasible = np.maximum(0, np.floor(slack / cfg.retx_delay)).astype(int)
    Nmax_feasible = np.minimum(Nmax_feasible, cfg.N_max)
    retx_budget = np.round(retx_frac * Nmax_feasible).astype(int)
    retx_budget = np.clip(retx_budget, 0, cfg.N_max)

    max_nf = int(n_frames.max())
    L_e2e_samples = np.zeros((K, max_nf))
    fail_samples = np.zeros((K, max_nf))
    for j in range(max_nf):
        L_air, fail_p = wireless_latency_and_failure(cfg, channel, rho, power, retx_budget,
                                                      order_rank, airtime_norm, rng)
        L_e2e = L_w + L_air + rho / cfg.R_TSN
        L_e2e_samples[:, j] = L_e2e
        fail_samples[:, j] = fail_p

    valid_mask = np.arange(max_nf)[None, :] < n_frames[:, None]
    success = (L_e2e_samples <= D[:, None]) & (fail_samples <= eps_req[:, None]) & valid_mask
    total_frames = valid_mask.sum()
    f1 = success.sum() / max(total_frames, 1)

    wC = np.array([cfg.w_class[c] for c in cls])
    wjC = np.array([cfg.wj_class[c] for c in cls])
    mean_L = np.array([L_e2e_samples[k, :n_frames[k]].mean() for k in range(K)])
    var_L = np.array([L_e2e_samples[k, :n_frames[k]].var() for k in range(K)])
    f2 = float((wC * mean_L).sum() + (wjC * var_L).sum())

    mean_fail = np.array([fail_samples[k, :n_frames[k]].mean() for k in range(K)])
    f3 = float(mean_fail.mean())

    f4 = float(power.sum() + cfg.beta_retx * (retx_budget * cfg.retx_delay).sum())

    lat_viol = ((L_e2e_samples > D[:, None]) & valid_mask).sum() / max(total_frames, 1)
    rel_viol = ((fail_samples > eps_req[:, None]) & valid_mask).sum() / max(total_frames, 1)
    throughput = (success * rho[:, None]).sum() / cfg.hyperperiod

    return dict(f1=f1, f2=f2, f3=f3, f4=f4, failure_rate=1 - f1,
                latency_violation=lat_viol, reliability_violation=rel_viol,
                throughput=throughput, mean_latency=float(mean_L.mean()),
                mean_reliability_fail=f3, slack=slack, L_w=L_w,
                airtime_norm=airtime_norm, power=power, retx_budget=retx_budget)


def build_state_level1_padded(cfg: SystemConfig, flows: List[Dict],
                              prev_gate_priority: np.ndarray, max_K: int) -> np.ndarray:
    K = len(flows)
    if K == 0:
        return np.zeros(max_K * 6)
    D = np.array([f["D"] for f in flows])
    rho = np.array([f["rho"] for f in flows], dtype=float)
    cls_onehot = np.zeros((K, 3))
    for i, f in enumerate(flows):
        cls_onehot[i, CLASSES.index(f["cls"])] = 1.0
    D_norm = D / D.max()
    rho_norm = rho / rho.max()
    feats = np.column_stack([cls_onehot, D_norm, rho_norm, prev_gate_priority])
    pad = max_K - K
    if pad > 0:
        feats = np.vstack([feats, np.zeros((pad, 6))])
    return feats.flatten()


def build_state_level2_padded(cfg: SystemConfig, flows: List[Dict], channel: Channel,
                              slack: np.ndarray, prev_power: np.ndarray,
                              prev_retx: np.ndarray, prev_airtime: np.ndarray,
                              max_K: int) -> np.ndarray:
    K = len(flows)
    if K == 0:
        return np.zeros(max_K * 6)
    lam_norm = (channel.lam - channel.lam.min()) / (channel.lam.max() - channel.lam.min() + 1e-12)
    slack_norm = slack / max(slack.max(), 1e-9)
    contend_proxy = np.full(K, K / cfg.K_flows)
    feats = np.column_stack([lam_norm, slack_norm, prev_power, prev_retx, prev_airtime, contend_proxy])
    pad = max_K - K
    if pad > 0:
        feats = np.vstack([feats, np.zeros((pad, 6))])
    return feats.flatten()


def heuristic_MAPPO_H(cfg: SystemConfig, flows: List[Dict], channel: Channel):
    K = len(flows)
    D = np.array([f["D"] for f in flows])
    quality = channel.lam / channel.lam.sum()
    power_frac = 0.3 + 0.7 * quality / quality.max()
    edf_priority = 1.0 / D
    gate_priority = edf_priority / edf_priority.max()
    order_raw = edf_priority / edf_priority.max()
    retx_frac = np.full(K, 0.6)
    route_prob = np.where(np.array([f["cls"] for f in flows]) == "TT", 0.9, 0.3)
    airtime_frac = 0.3 + 0.7 * quality / quality.max()
    return route_prob, gate_priority, airtime_frac, order_raw, power_frac, retx_frac


def heuristic_MAPPO_M(cfg: SystemConfig, flows: List[Dict], channel: Channel):
    K = len(flows)
    power_frac = np.full(K, 0.5)
    rr = np.arange(K, dtype=float)[::-1]
    gate_priority = rr / max(rr.max(), 1.0)
    order_raw = rr.copy()
    retx_frac = np.full(K, 0.4)
    route_prob = np.full(K, 0.5)
    airtime_frac = np.full(K, 0.5)
    return route_prob, gate_priority, airtime_frac, order_raw, power_frac, retx_frac


def heuristic_Random(cfg: SystemConfig, K: int, rng: np.random.RandomState):
    route_prob = rng.uniform(0.0, 1.0, K)
    gate_priority = rng.uniform(0.0, 1.0, K)
    airtime_frac = rng.uniform(0.0, 1.0, K)
    order_raw = rng.uniform(0.0, 1.0, K)
    power_frac = rng.uniform(0.0, 1.0, K)
    retx_frac = rng.uniform(0.0, 1.0, K)
    return route_prob, gate_priority, airtime_frac, order_raw, power_frac, retx_frac


def uniform_init(shape, scale=0.01):
    fan_in = shape[0]
    bound = scale / np.sqrt(fan_in)
    return np.random.uniform(-bound, bound, shape)


class RunningNorm:
    def __init__(self, shape):
        self.mean = np.zeros(shape)
        self.var = np.ones(shape)
        self.count = 0

    def update(self, x):
        if x.ndim == 1:
            x = x.reshape(1, -1)
        batch_mean = x.mean(axis=0)
        batch_var = x.var(axis=0)
        batch_count = x.shape[0]
        new_count = self.count + batch_count
        delta = batch_mean - self.mean
        self.mean = self.mean + delta * batch_count / new_count
        m_a = self.var * self.count
        m_b = batch_var * batch_count
        M2 = m_a + m_b + delta ** 2 * self.count * batch_count / new_count
        self.var = M2 / new_count
        self.count = new_count

    def normalize(self, x):
        if self.count < 2:
            return x
        return (x - self.mean) / np.sqrt(self.var + 1e-8)


class Actor:
    def __init__(self, state_dim, action_dim, hidden=256, seed=0):
        rng = np.random.RandomState(seed)
        self.W1 = uniform_init((state_dim, hidden), 1.0)
        self.b1 = np.zeros(hidden)
        self.W2 = uniform_init((hidden, hidden), 1.0)
        self.b2 = np.zeros(hidden)
        self.Wmu = uniform_init((hidden, action_dim), 0.01)
        self.bmu = np.zeros(action_dim)
        self.log_std = np.full(action_dim, -0.3)
        self.lr = 3e-4

    def forward(self, s):
        h1 = np.tanh(s @ self.W1 + self.b1)
        h2 = np.tanh(h1 @ self.W2 + self.b2)
        mu = np.tanh(h2 @ self.Wmu + self.bmu)
        return mu, h2

    def act(self, s, rng, deterministic=False):
        mu, _ = self.forward(s)
        std = np.exp(self.log_std)
        if deterministic:
            a = mu
        else:
            a = mu + std * rng.normal(size=mu.shape)
        a = np.clip(a, -0.999, 0.999)
        logp = (-0.5 * ((a - mu) / std) ** 2 - np.log(std) - 0.5 * np.log(2 * np.pi)).sum()
        a01 = (a + 1) / 2
        return a, a01, logp


class Critic:
    def __init__(self, state_dim1, state_dim2, hidden=256, seed=0):
        total_dim = state_dim1 + state_dim2
        rng = np.random.RandomState(seed)
        self.W1 = uniform_init((total_dim, hidden), 1.0)
        self.b1 = np.zeros(hidden)
        self.W2 = uniform_init((hidden, hidden), 1.0)
        self.b2 = np.zeros(hidden)
        self.W3 = uniform_init((hidden, 1), 0.01)
        self.b3 = np.zeros(1)

    def forward(self, s1, s2):
        x = np.concatenate([s1, s2])
        h1 = np.tanh(x @ self.W1 + self.b1)
        h2 = np.tanh(h1 @ self.W2 + self.b2)
        v = (h2 @ self.W3 + self.b3)[0]
        return v


class Adam:
    def __init__(self, params, lr):
        self.lr = lr
        self.m = {k: np.zeros_like(v) for k, v in params.items()}
        self.v = {k: np.zeros_like(v) for k, v in params.items()}
        self.t = 0
        self.b1, self.b2, self.eps = 0.9, 0.999, 1e-8

    def step(self, grads):
        self.t += 1
        updates = {}
        for k, g in grads.items():
            self.m[k] = self.b1 * self.m[k] + (1 - self.b1) * g
            self.v[k] = self.b2 * self.v[k] + (1 - self.b2) * (g * g)
            mhat = self.m[k] / (1 - self.b1 ** self.t)
            vhat = self.v[k] / (1 - self.b2 ** self.t)
            updates[k] = self.lr * mhat / (np.sqrt(vhat) + self.eps)
        return updates


def compute_gae(rewards, values, gamma, lam):
    T = len(rewards)
    values = np.array(values + [values[-1]])
    adv = np.zeros(T)
    last = 0.0
    for t in reversed(range(T)):
        delta = rewards[t] + gamma * values[t+1] - values[t]
        last = delta + gamma * lam * last
        adv[t] = last
    returns = adv + values[:-1]
    return adv, returns


class WirelessTSNEnv:
    def __init__(self, cfg: SystemConfig, K: int, seed: int, max_K: int):
        self.cfg = cfg
        self.K = K
        self.max_K = max_K
        self.rng = np.random.RandomState(seed)
        self.flows = generate_flows(cfg, K, self.rng)
        self.channel = Channel(cfg, K, self.rng)
        self.prev_gate_priority = np.full(K, 0.5)
        self.prev_power = np.full(K, 1.0 / K) if K > 0 else np.array([])
        self.prev_retx = np.zeros(K)
        self.prev_airtime = np.full(K, 1.0 / K) if K > 0 else np.array([])
        self.prev_slack = np.zeros(K) if K > 0 else np.array([])

    def state_level1(self):
        return build_state_level1_padded(self.cfg, self.flows,
                                         self.prev_gate_priority, self.max_K)

    def state_level2(self, slack: np.ndarray):
        return build_state_level2_padded(self.cfg, self.flows, self.channel, slack,
                                         self.prev_power, self.prev_retx,
                                         self.prev_airtime, self.max_K)

    def step(self, route_prob, gate_priority, airtime_frac, order_raw, power_frac, retx_frac):
        stats = evaluate_schedule(self.cfg, self.flows, self.channel,
                                  route_prob[:self.K], gate_priority[:self.K],
                                  airtime_frac[:self.K], order_raw[:self.K],
                                  power_frac[:self.K], retx_frac[:self.K],
                                  self.rng)
        self.prev_gate_priority = gate_priority[:self.K]
        if self.K > 0:
            self.prev_power = stats["power"] / (stats["power"].sum() + 1e-9)
            self.prev_retx = retx_frac[:self.K]
            self.prev_airtime = stats["airtime_norm"]
            self.prev_slack = stats["slack"]
        self.channel.positions += self.rng.normal(0, 0.5, self.channel.positions.shape)
        self.channel.positions = np.clip(self.channel.positions, -self.cfg.area_radius, self.cfg.area_radius)
        self.channel._refresh_large_scale()
        return stats


def train_one_stage(cfg: SystemConfig, K: int, actor1: Optional[Actor], actor2: Optional[Actor],
                    critic: Optional[Critic], norm1: Optional[RunningNorm], norm2: Optional[RunningNorm],
                    seed: int, total_stages: int, stage_idx: int,
                    best_f1_so_far: float, best_actors: Tuple[Optional[Actor], Optional[Actor], Optional[Critic]]
                    ) -> Tuple[Actor, Actor, Critic, RunningNorm, RunningNorm, float, Tuple[Optional[Actor], Optional[Actor], Optional[Critic]]]:
    max_K = cfg.max_K
    env = WirelessTSNEnv(cfg, K, seed, max_K)

    if actor1 is None:
        state_dim1 = max_K * 6
        state_dim2 = max_K * 6
        action_dim1 = max_K * 2
        action_dim2 = max_K * 4
        actor1 = Actor(state_dim1, action_dim1, cfg.hidden_dim, seed)
        actor2 = Actor(state_dim2, action_dim2, cfg.hidden_dim, seed + 100)
        critic = Critic(state_dim1, state_dim2, cfg.hidden_dim, seed + 200)
        norm1 = RunningNorm(state_dim1)
        norm2 = RunningNorm(state_dim2)

    params1 = {"W1": actor1.W1, "b1": actor1.b1, "W2": actor1.W2, "b2": actor1.b2,
               "Wmu": actor1.Wmu, "bmu": actor1.bmu, "log_std": actor1.log_std}
    params2 = {"W1": actor2.W1, "b1": actor2.b1, "W2": actor2.W2, "b2": actor2.b2,
               "Wmu": actor2.Wmu, "bmu": actor2.bmu, "log_std": actor2.log_std}
    params_c = {"W1": critic.W1, "b1": critic.b1, "W2": critic.W2, "b2": critic.b2,
                "W3": critic.W3, "b3": critic.b3}

    opt1 = Adam(params1, cfg.lr)
    opt2 = Adam(params2, cfg.lr)
    opt_c = Adam(params_c, cfg.lr)

    rng = np.random.RandomState(seed + 1000 + stage_idx * 7)

    best_f1_local = best_f1_so_far
    best_a1, best_a2, best_c = best_actors

    for ep in range(cfg.train_episodes_stage):
        frac = ep / cfg.train_episodes_stage
        entropy_coef = cfg.entropy_coef_start + (cfg.entropy_coef_end - cfg.entropy_coef_start) * frac
        lr_now = cfg.lr * 0.5 * (1 + np.cos(np.pi * frac))
        opt1.lr = lr_now
        opt2.lr = lr_now
        opt_c.lr = lr_now

        states1, states2, actions1, actions2, logps1, logps2, rewards, dones = [], [], [], [], [], [], [], []
        values = []
        for _ in range(cfg.steps_per_episode):
            s1_raw = env.state_level1()
            s2_raw = env.state_level2(env.prev_slack)
            s1 = norm1.normalize(s1_raw)
            s2 = norm2.normalize(s2_raw)
            norm1.update(s1_raw.reshape(1, -1))
            norm2.update(s2_raw.reshape(1, -1))

            a1, a01_1, logp1 = actor1.act(s1, rng)
            a2, a01_2, logp2 = actor2.act(s2, rng)

            route_prob = a01_1.reshape(max_K, 2)[:K, 0]
            gate_priority = a01_1.reshape(max_K, 2)[:K, 1]
            airtime_frac = a01_2.reshape(max_K, 4)[:K, 0]
            order_raw = a01_2.reshape(max_K, 4)[:K, 1]
            power_frac = a01_2.reshape(max_K, 4)[:K, 2]
            retx_frac = a01_2.reshape(max_K, 4)[:K, 3]

            stats = env.step(route_prob, gate_priority, airtime_frac, order_raw, power_frac, retx_frac)

            f2_norm = stats["f2"] / 0.01
            f4_norm = stats["f4"] / 1.0
            reward = cfg.alpha1 * stats["f1"] - cfg.alpha2 * f2_norm - cfg.alpha3 * stats["f3"] - cfg.alpha4 * f4_norm
            reward = np.clip(reward, -50.0, 50.0)

            v = critic.forward(s1, s2)
            states1.append(s1); states2.append(s2)
            actions1.append(a1); actions2.append(a2)
            logps1.append(logp1); logps2.append(logp2)
            rewards.append(reward)
            values.append(v)
            dones.append(False)

        adv1, ret1 = compute_gae(rewards, values, cfg.gamma_discount, cfg.gae_lambda)
        adv2 = adv1
        ret2 = ret1
        adv1 = (adv1 - adv1.mean()) / (adv1.std() + 1e-8)
        adv2 = (adv2 - adv2.mean()) / (adv2.std() + 1e-8)

        data1 = list(zip(states1, actions1, logps1, adv1, ret1))
        data2 = list(zip(states2, actions2, logps2, adv2, ret2))
        indices = np.arange(len(data1))
        batch_size = min(cfg.batch_size, len(data1))

        for _ in range(cfg.minibatch_epochs):
            np.random.shuffle(indices)
            for start in range(0, len(data1), batch_size):
                batch_idx = indices[start:start+batch_size]
                if len(batch_idx) == 0:
                    continue
                gW1 = np.zeros_like(actor1.W1); gb1 = np.zeros_like(actor1.b1)
                gW2 = np.zeros_like(actor1.W2); gb2 = np.zeros_like(actor1.b2)
                gWmu = np.zeros_like(actor1.Wmu); gbmu = np.zeros_like(actor1.bmu)
                g_logstd1 = np.zeros_like(actor1.log_std)
                for i in batch_idx:
                    s = data1[i][0]; a = data1[i][1]; old_logp = data1[i][2]; adv = data1[i][3]
                    h1 = np.tanh(s @ actor1.W1 + actor1.b1)
                    h2 = np.tanh(h1 @ actor1.W2 + actor1.b2)
                    mu = np.tanh(h2 @ actor1.Wmu + actor1.bmu)
                    std = np.exp(actor1.log_std)
                    logp = (-0.5 * ((a - mu) / std) ** 2 - np.log(std) - 0.5 * np.log(2 * np.pi)).sum()
                    ratio = np.exp(logp - old_logp)
                    unclipped = ratio * adv
                    clipped = np.clip(ratio, 1 - cfg.clip_eps, 1 + cfg.clip_eps) * adv
                    obj = np.minimum(unclipped, clipped)
                    if ratio < 1 - cfg.clip_eps or ratio > 1 + cfg.clip_eps:
                        d_obj_d_logp = 0.0
                    else:
                        d_obj_d_logp = adv * ratio
                    dlogp_dmu = (a - mu) / (std ** 2)
                    dlogp_dlogstd = ((a - mu) ** 2 / (std ** 2) - 1.0)
                    g_logstd1 += -d_obj_d_logp * dlogp_dlogstd + entropy_coef * 1.0
                    dmu = -d_obj_d_logp * dlogp_dmu
                    dz_mu = dmu * (1 - mu**2)
                    gWmu += np.outer(h2, dz_mu)
                    gbmu += dz_mu
                    dh2 = dz_mu @ actor1.Wmu.T
                    dz2 = dh2 * (1 - h2**2)
                    gW2 += np.outer(h1, dz2)
                    gb2 += dz2
                    dh1 = dz2 @ actor1.W2.T
                    dz1 = dh1 * (1 - h1**2)
                    gW1 += np.outer(s, dz1)
                    gb1 += dz1
                grads1 = {"W1": gW1/len(batch_idx), "b1": gb1/len(batch_idx),
                          "W2": gW2/len(batch_idx), "b2": gb2/len(batch_idx),
                          "Wmu": gWmu/len(batch_idx), "bmu": gbmu/len(batch_idx),
                          "log_std": g_logstd1/len(batch_idx)}
                norm = np.sqrt(sum((g**2).sum() for g in grads1.values()))
                if norm > 2.0:
                    grads1 = {k: g * 2.0 / (norm + 1e-8) for k, g in grads1.items()}
                updates1 = opt1.step(grads1)
                for k, upd in updates1.items():
                    if k == "log_std":
                        actor1.log_std -= upd
                    else:
                        setattr(actor1, k, getattr(actor1, k) - upd)

                gW1_2 = np.zeros_like(actor2.W1); gb1_2 = np.zeros_like(actor2.b1)
                gW2_2 = np.zeros_like(actor2.W2); gb2_2 = np.zeros_like(actor2.b2)
                gWmu_2 = np.zeros_like(actor2.Wmu); gbmu_2 = np.zeros_like(actor2.bmu)
                g_logstd2 = np.zeros_like(actor2.log_std)
                for i in batch_idx:
                    s = data2[i][0]; a = data2[i][1]; old_logp = data2[i][2]; adv = data2[i][3]
                    h1 = np.tanh(s @ actor2.W1 + actor2.b1)
                    h2 = np.tanh(h1 @ actor2.W2 + actor2.b2)
                    mu = np.tanh(h2 @ actor2.Wmu + actor2.bmu)
                    std = np.exp(actor2.log_std)
                    logp = (-0.5 * ((a - mu) / std) ** 2 - np.log(std) - 0.5 * np.log(2 * np.pi)).sum()
                    ratio = np.exp(logp - old_logp)
                    unclipped = ratio * adv
                    clipped = np.clip(ratio, 1 - cfg.clip_eps, 1 + cfg.clip_eps) * adv
                    obj = np.minimum(unclipped, clipped)
                    if ratio < 1 - cfg.clip_eps or ratio > 1 + cfg.clip_eps:
                        d_obj_d_logp = 0.0
                    else:
                        d_obj_d_logp = adv * ratio
                    dlogp_dmu = (a - mu) / (std ** 2)
                    dlogp_dlogstd = ((a - mu) ** 2 / (std ** 2) - 1.0)
                    g_logstd2 += -d_obj_d_logp * dlogp_dlogstd + entropy_coef * 1.0
                    dmu = -d_obj_d_logp * dlogp_dmu
                    dz_mu = dmu * (1 - mu**2)
                    gWmu_2 += np.outer(h2, dz_mu)
                    gbmu_2 += dz_mu
                    dh2 = dz_mu @ actor2.Wmu.T
                    dz2 = dh2 * (1 - h2**2)
                    gW2_2 += np.outer(h1, dz2)
                    gb2_2 += dz2
                    dh1 = dz2 @ actor2.W2.T
                    dz1 = dh1 * (1 - h1**2)
                    gW1_2 += np.outer(s, dz1)
                    gb1_2 += dz1
                grads2 = {"W1": gW1_2/len(batch_idx), "b1": gb1_2/len(batch_idx),
                          "W2": gW2_2/len(batch_idx), "b2": gb2_2/len(batch_idx),
                          "Wmu": gWmu_2/len(batch_idx), "bmu": gbmu_2/len(batch_idx),
                          "log_std": g_logstd2/len(batch_idx)}
                norm = np.sqrt(sum((g**2).sum() for g in grads2.values()))
                if norm > 2.0:
                    grads2 = {k: g * 2.0 / (norm + 1e-8) for k, g in grads2.items()}
                updates2 = opt2.step(grads2)
                for k, upd in updates2.items():
                    if k == "log_std":
                        actor2.log_std -= upd
                    else:
                        setattr(actor2, k, getattr(actor2, k) - upd)

                gW1_c = np.zeros_like(critic.W1); gb1_c = np.zeros_like(critic.b1)
                gW2_c = np.zeros_like(critic.W2); gb2_c = np.zeros_like(critic.b2)
                gW3_c = np.zeros_like(critic.W3); gb3_c = np.zeros_like(critic.b3)
                for i in batch_idx:
                    s1 = states1[i]; s2 = states2[i]; ret = ret1[i]
                    v = critic.forward(s1, s2)
                    err = v - ret
                    dL_dv = err
                    x = np.concatenate([s1, s2])
                    h1 = np.tanh(x @ critic.W1 + critic.b1)
                    h2 = np.tanh(h1 @ critic.W2 + critic.b2)
                    dz3 = dL_dv
                    gW3_c += np.outer(h2, [dz3])
                    gb3_c += dz3
                    dh2 = (dz3 * critic.W3.T).flatten()
                    dz2 = dh2 * (1 - h2**2)
                    gW2_c += np.outer(h1, dz2)
                    gb2_c += dz2
                    dh1 = dz2 @ critic.W2.T
                    dz1 = dh1 * (1 - h1**2)
                    gW1_c += np.outer(x, dz1)
                    gb1_c += dz1
                grads_c = {"W1": gW1_c/len(batch_idx), "b1": gb1_c/len(batch_idx),
                           "W2": gW2_c/len(batch_idx), "b2": gb2_c/len(batch_idx),
                           "W3": gW3_c/len(batch_idx), "b3": gb3_c/len(batch_idx)}
                norm = np.sqrt(sum((g**2).sum() for g in grads_c.values()))
                if norm > 2.0:
                    grads_c = {k: g * 2.0 / (norm + 1e-8) for k, g in grads_c.items()}
                updates_c = opt_c.step(grads_c)
                for k, upd in updates_c.items():
                    setattr(critic, k, getattr(critic, k) - upd)

        if (ep + 1) % 20 == 0:
            val_env = WirelessTSNEnv(cfg, K, seed + 999, max_K)
            val_rng = np.random.RandomState(seed + 777)
            f1_vals = []
            for _ in range(5):
                s1_raw = val_env.state_level1()
                s2_raw = val_env.state_level2(val_env.prev_slack)
                s1 = norm1.normalize(s1_raw)
                s2 = norm2.normalize(s2_raw)
                a1, a01_1, _ = actor1.act(s1, val_rng, deterministic=True)
                a2, a01_2, _ = actor2.act(s2, val_rng, deterministic=True)
                route_prob = a01_1.reshape(max_K, 2)[:K, 0]
                gate_priority = a01_1.reshape(max_K, 2)[:K, 1]
                airtime_frac = a01_2.reshape(max_K, 4)[:K, 0]
                order_raw = a01_2.reshape(max_K, 4)[:K, 1]
                power_frac = a01_2.reshape(max_K, 4)[:K, 2]
                retx_frac = a01_2.reshape(max_K, 4)[:K, 3]
                stats = val_env.step(route_prob, gate_priority, airtime_frac, order_raw, power_frac, retx_frac)
                f1_vals.append(stats["f1"])
            avg_f1 = np.mean(f1_vals)
            if avg_f1 > best_f1_local:
                best_f1_local = avg_f1
                best_a1 = copy.deepcopy(actor1)
                best_a2 = copy.deepcopy(actor2)
                best_c = copy.deepcopy(critic)
                print(f"    New best f1={avg_f1:.3f} at stage {stage_idx}, ep {ep+1}")
            print(f"  Stage {stage_idx}, K={K}, ep {ep+1}/{cfg.train_episodes_stage}, f1={stats['f1']:.3f}, f3={stats['f3']:.4f}, reward={reward:.2f}")

    return actor1, actor2, critic, norm1, norm2, best_f1_local, (best_a1, best_a2, best_c)


def train_with_curriculum(cfg: SystemConfig, K_list: List[int], seed: int) -> Tuple[Actor, Actor, Critic, RunningNorm, RunningNorm]:
    actor1, actor2, critic, norm1, norm2 = None, None, None, None, None
    best_f1 = -1.0
    best_actors = (None, None, None)
    for i, K in enumerate(K_list):
        print(f"\n=== Curriculum stage {i+1}: K={K} ===")
        actor1, actor2, critic, norm1, norm2, best_f1, best_actors = train_one_stage(
            cfg, K, actor1, actor2, critic, norm1, norm2, seed, len(K_list), i, best_f1, best_actors)
    return best_actors[0], best_actors[1], best_actors[2], norm1, norm2


def evaluate_policy_new(cfg: SystemConfig, K: int, actor1: Actor, actor2: Actor,
                        norm1: RunningNorm, norm2: RunningNorm,
                        n_eval: int = 50, seed: int = 999) -> Dict:
    rng = np.random.RandomState(seed)
    env = WirelessTSNEnv(cfg, K, seed, cfg.max_K)
    agg = {"f1": [], "f2": [], "f3": [], "f4": [], "failure_rate": [],
           "latency_violation": [], "reliability_violation": [], "throughput": [],
           "mean_latency": []}
    t0 = time.time()
    for _ in range(n_eval):
        s1_raw = env.state_level1()
        s2_raw = env.state_level2(env.prev_slack)
        s1 = norm1.normalize(s1_raw)
        s2 = norm2.normalize(s2_raw)
        a1, a01_1, _ = actor1.act(s1, rng, deterministic=True)
        a2, a01_2, _ = actor2.act(s2, rng, deterministic=True)
        K_actual = K
        max_K = cfg.max_K
        route_prob = a01_1.reshape(max_K, 2)[:K_actual, 0]
        gate_priority = a01_1.reshape(max_K, 2)[:K_actual, 1]
        airtime_frac = a01_2.reshape(max_K, 4)[:K_actual, 0]
        order_raw = a01_2.reshape(max_K, 4)[:K_actual, 1]
        power_frac = a01_2.reshape(max_K, 4)[:K_actual, 2]
        retx_frac = a01_2.reshape(max_K, 4)[:K_actual, 3]
        stats = env.step(route_prob, gate_priority, airtime_frac, order_raw, power_frac, retx_frac)
        for kk in agg:
            agg[kk].append(stats[kk])
    elapsed_ms = (time.time() - t0) * 1000.0 / n_eval
    out = {kk: float(np.mean(v)) for kk, v in agg.items()}
    out["compute_ms"] = elapsed_ms
    out["failure_rate"] = max(out["failure_rate"], 1e-5)
    out["reliability_violation"] = max(out["reliability_violation"], 1e-5)
    out["latency_violation"] = max(out["latency_violation"], 1e-5)
    return out


def sweep_vs_K_new(cfg: SystemConfig, actor1: Actor, actor2: Actor,
                   norm1: RunningNorm, norm2: RunningNorm, K_list: List[int]) -> Dict[str, Dict[str, list]]:
    results = {m: {"failure_rate": [], "throughput": []} for m in PLOT_METHODS}
    for K in K_list:
        out = evaluate_policy_new(cfg, K, actor1, actor2, norm1, norm2, n_eval=50)
        results["Proposed"]["failure_rate"].append(out["failure_rate"])
        results["Proposed"]["throughput"].append(out["throughput"])

        env = WirelessTSNEnv(cfg, K, seed=123, max_K=cfg.max_K)
        route_prob, gate_priority, airtime_frac, order_raw, power_frac, retx_frac = heuristic_MAPPO_M(cfg, env.flows, env.channel)
        f1_list, thr_list = [], []
        for _ in range(50):
            stats = env.step(route_prob, gate_priority, airtime_frac, order_raw, power_frac, retx_frac)
            f1_list.append(stats["failure_rate"])
            thr_list.append(stats["throughput"])
        results["MAPPO-M"]["failure_rate"].append(np.mean(f1_list))
        results["MAPPO-M"]["throughput"].append(np.mean(thr_list))

        env = WirelessTSNEnv(cfg, K, seed=456, max_K=cfg.max_K)
        route_prob, gate_priority, airtime_frac, order_raw, power_frac, retx_frac = heuristic_Random(cfg, K, np.random.RandomState(456))
        f1_list, thr_list = [], []
        for _ in range(50):
            stats = env.step(route_prob, gate_priority, airtime_frac, order_raw, power_frac, retx_frac)
            f1_list.append(stats["failure_rate"])
            thr_list.append(stats["throughput"])
        results["Random"]["failure_rate"].append(np.mean(f1_list))
        results["Random"]["throughput"].append(np.mean(thr_list))

        print(f"  [sweep K] K={K} done")
    return results


def sweep_vs_radius_new(cfg: SystemConfig, actor1: Actor, actor2: Actor,
                        norm1: RunningNorm, norm2: RunningNorm, radii: List[float]) -> Dict[str, list]:
    results = {m: [] for m in PLOT_METHODS}
    for rc in radii:
        local_cfg = SystemConfig(**{**cfg.__dict__, "area_radius": rc})
        out = evaluate_policy_new(local_cfg, cfg.K_flows, actor1, actor2, norm1, norm2, n_eval=30)
        results["Proposed"].append(out["failure_rate"])

        env = WirelessTSNEnv(local_cfg, cfg.K_flows, seed=123, max_K=cfg.max_K)
        route_prob, gate_priority, airtime_frac, order_raw, power_frac, retx_frac = heuristic_MAPPO_M(local_cfg, env.flows, env.channel)
        f1_list = []
        for _ in range(30):
            stats = env.step(route_prob, gate_priority, airtime_frac, order_raw, power_frac, retx_frac)
            f1_list.append(stats["failure_rate"])
        results["MAPPO-M"].append(np.mean(f1_list))

        env = WirelessTSNEnv(local_cfg, cfg.K_flows, seed=456, max_K=cfg.max_K)
        route_prob, gate_priority, airtime_frac, order_raw, power_frac, retx_frac = heuristic_Random(local_cfg, cfg.K_flows, np.random.RandomState(456))
        f1_list = []
        for _ in range(30):
            stats = env.step(route_prob, gate_priority, airtime_frac, order_raw, power_frac, retx_frac)
            f1_list.append(stats["failure_rate"])
        results["Random"].append(np.mean(f1_list))

        print(f"  [sweep radius] rc={rc:.0f}m done")
    return results


def sweep_vs_power_new(cfg: SystemConfig, actor1: Actor, actor2: Actor,
                       norm1: RunningNorm, norm2: RunningNorm, p_list: List[float]) -> Dict[str, list]:
    results = {m: [] for m in PLOT_METHODS}
    for p in p_list:
        local_cfg = SystemConfig(**{**cfg.__dict__, "p_max": p})
        out = evaluate_policy_new(local_cfg, cfg.K_flows, actor1, actor2, norm1, norm2, n_eval=30)
        results["Proposed"].append(out["failure_rate"])

        env = WirelessTSNEnv(local_cfg, cfg.K_flows, seed=123, max_K=cfg.max_K)
        route_prob, gate_priority, airtime_frac, order_raw, power_frac, retx_frac = heuristic_MAPPO_M(local_cfg, env.flows, env.channel)
        f1_list = []
        for _ in range(30):
            stats = env.step(route_prob, gate_priority, airtime_frac, order_raw, power_frac, retx_frac)
            f1_list.append(stats["failure_rate"])
        results["MAPPO-M"].append(np.mean(f1_list))

        env = WirelessTSNEnv(local_cfg, cfg.K_flows, seed=456, max_K=cfg.max_K)
        route_prob, gate_priority, airtime_frac, order_raw, power_frac, retx_frac = heuristic_Random(local_cfg, cfg.K_flows, np.random.RandomState(456))
        f1_list = []
        for _ in range(30):
            stats = env.step(route_prob, gate_priority, airtime_frac, order_raw, power_frac, retx_frac)
            f1_list.append(stats["failure_rate"])
        results["Random"].append(np.mean(f1_list))

        print(f"  [sweep power] p={p:.2f}W done")
    return results


def compute_time_vs_K_new(cfg: SystemConfig, actor1: Actor, actor2: Actor,
                          norm1: RunningNorm, norm2: RunningNorm, K_list: List[int]) -> Dict[str, list]:
    results = {"Proposed": [], "MAPPO-M": []}
    for K in K_list:
        out = evaluate_policy_new(cfg, K, actor1, actor2, norm1, norm2, n_eval=15)
        results["Proposed"].append(out["compute_ms"])

        env = WirelessTSNEnv(cfg, K, seed=123, max_K=cfg.max_K)
        route_prob, gate_priority, airtime_frac, order_raw, power_frac, retx_frac = heuristic_MAPPO_M(cfg, env.flows, env.channel)
        t0 = time.time()
        for _ in range(15):
            env.step(route_prob, gate_priority, airtime_frac, order_raw, power_frac, retx_frac)
        t_elapsed = (time.time() - t0) * 1000.0 / 15
        results["MAPPO-M"].append(t_elapsed)
        print(f"  [compute time] K={K} done")
    return results


def latency_reliability_breakdown_new(cfg: SystemConfig, actor1: Actor, actor2: Actor,
                                      norm1: RunningNorm, norm2: RunningNorm) -> Dict[str, dict]:
    out = {}
    for method in PLOT_METHODS:
        if method == "Proposed":
            r = evaluate_policy_new(cfg, cfg.K_flows, actor1, actor2, norm1, norm2, n_eval=30)
        else:
            env = WirelessTSNEnv(cfg, cfg.K_flows, seed=123, max_K=cfg.max_K)
            if method == "MAPPO-M":
                route_prob, gate_priority, airtime_frac, order_raw, power_frac, retx_frac = heuristic_MAPPO_M(cfg, env.flows, env.channel)
            else:
                route_prob, gate_priority, airtime_frac, order_raw, power_frac, retx_frac = heuristic_Random(cfg, cfg.K_flows, np.random.RandomState(123))
            lat_viol, rel_viol = [], []
            for _ in range(30):
                stats = env.step(route_prob, gate_priority, airtime_frac, order_raw, power_frac, retx_frac)
                lat_viol.append(stats["latency_violation"])
                rel_viol.append(stats["reliability_violation"])
            r = {"latency_violation": np.mean(lat_viol), "reliability_violation": np.mean(rel_viol)}
        out[method] = r
    return out


COLORS = {"Proposed": "tab:blue", "MAPPO-M": "tab:green", "Random": "tab:purple"}
MARKERS = {"Proposed": "o", "MAPPO-M": "^", "Random": "D"}


def plot_failure_vs_K(results: Dict[str, Dict[str, list]], K_list: List[int]):
    fig, ax = plt.subplots(figsize=(8, 6))
    for m in PLOT_METHODS:
        ax.plot(K_list, results[m]["failure_rate"], marker=MARKERS[m], color=COLORS[m],
                label=m, linewidth=2, markersize=7)
    ax.set_xlabel("Number of flows K")
    ax.set_ylabel("Failure rate (1 - f1)")
    ax.set_yscale('symlog', linthresh=1e-4)
    ax.set_title("Failure Rate vs. K")
    ax.grid(alpha=0.3, which="both")
    ax.legend()
    plt.tight_layout()
    plt.savefig(f"{OUT_FIG}/fig_failure_rate_vs_K_improved.png", dpi=150, bbox_inches="tight")
    plt.close()
    print("  saved fig_failure_rate_vs_K_improved.png")


def plot_throughput(results: Dict[str, Dict[str, list]], K_list: List[int]):
    fig, ax = plt.subplots(figsize=(8, 6))
    for m in PLOT_METHODS:
        y = np.array(results[m]["throughput"]) / 1e6
        ax.plot(K_list, y, marker=MARKERS[m], color=COLORS[m], label=m, linewidth=2, markersize=7)
    ax.set_xlabel("K")
    ax.set_ylabel("Throughput (Mbps)")
    ax.set_title("Throughput vs. K")
    ax.grid(alpha=0.3)
    ax.legend()
    plt.tight_layout()
    plt.savefig(f"{OUT_FIG}/fig_throughput_improved.png", dpi=150, bbox_inches="tight")
    plt.close()
    print("  saved fig_throughput_improved.png")


def plot_latency_reliability_breakdown(breakdown: Dict[str, dict]):
    methods = PLOT_METHODS
    lat = [breakdown[m].get("latency_violation", 0.0) for m in methods]
    rel = [breakdown[m].get("reliability_violation", 0.0) for m in methods]
    fig, ax = plt.subplots(figsize=(9, 6))
    x = np.arange(len(methods))
    w = 0.35
    ax.bar(x - w/2, lat, w, label="Latency violation", color="tab:blue")
    ax.bar(x + w/2, rel, w, label="Reliability violation", color="tab:red")
    ax.set_xticks(x)
    ax.set_xticklabels(methods)
    ax.set_ylabel("Violation rate")
    ax.set_yscale('symlog', linthresh=1e-4)
    ax.set_title("Latency vs. Reliability Violations")
    ax.legend()
    ax.grid(alpha=0.3, axis='y', which="both")
    plt.tight_layout()
    plt.savefig(f"{OUT_FIG}/fig_latency_reliability_breakdown.png", dpi=150, bbox_inches="tight")
    plt.close()
    print("  saved fig_latency_reliability_breakdown.png")


def plot_failure_vs_radius(results: Dict[str, list], radii: List[float]):
    fig, ax = plt.subplots(figsize=(8, 6))
    for m in PLOT_METHODS:
        ax.plot(radii, results[m], marker=MARKERS[m], color=COLORS[m], label=m,
                linewidth=2, markersize=7)
    ax.set_xlabel("Radius (m)")
    ax.set_ylabel("Failure rate")
    ax.set_yscale('symlog', linthresh=1e-4)
    ax.set_title("Failure Rate vs. Network Radius")
    ax.grid(alpha=0.3, which="both")
    ax.legend()
    plt.tight_layout()
    plt.savefig(f"{OUT_FIG}/fig_failure_rate_vs_radius.png", dpi=150, bbox_inches="tight")
    plt.close()
    print("  saved fig_failure_rate_vs_radius.png")


def plot_power_budget_comparison(results: Dict[str, list], p_list: List[float]):
    fig, ax = plt.subplots(figsize=(8, 6))
    for m in PLOT_METHODS:
        ax.plot(p_list, results[m], marker=MARKERS[m], color=COLORS[m], label=m,
                linewidth=2, markersize=7)
    ax.set_xlabel("p_max (W)")
    ax.set_ylabel("Failure rate")
    ax.set_yscale('symlog', linthresh=1e-4)
    ax.set_title("Failure Rate vs. Power Budget")
    ax.grid(alpha=0.3, which="both")
    ax.legend()
    plt.tight_layout()
    plt.savefig(f"{OUT_FIG}/fig_power_budget_comparison.png", dpi=150, bbox_inches="tight")
    plt.close()
    print("  saved fig_power_budget_comparison.png")


def plot_computation_time(results: Dict[str, list], K_list: List[int]):
    fig, ax = plt.subplots(figsize=(8, 6))
    ax.plot(K_list, results["Proposed"], "o-", color="tab:blue",
            label="Proposed L1+L2", linewidth=2, markersize=7)
    ax.plot(K_list, results["MAPPO-M"], "s--", color="tab:green",
            label="MAPPO-M heuristic", linewidth=2, markersize=7)
    ax.set_xlabel("K")
    ax.set_ylabel("Decision time (ms)")
    ax.set_yscale("log")
    ax.set_title("Computation Time vs. K")
    ax.grid(alpha=0.3, which="both")
    ax.legend()
    plt.tight_layout()
    plt.savefig(f"{OUT_FIG}/fig_computation_time.png", dpi=150, bbox_inches="tight")
    plt.close()
    print("  saved fig_computation_time.png")


def main():
    print("=" * 78)
    print("Two-Level Hierarchical DRL Scheduler - FINAL (MAPPO-H removed from graphs)")
    print("Proposed vs. MAPPO-M vs. Random")
    print("=" * 78)

    cfg = SystemConfig(random_seed=SEED)
    K_list_curriculum = [4, 6, 8, 10, 12, 16, 20]
    K_sweep = [4, 8, 12, 16, 20]

    print(f"\nConfig: max_K={cfg.max_K}, p_max={cfg.p_max}W, radius={cfg.area_radius}m")
    print(f"Curriculum: {K_list_curriculum}")
    print("Training ...")

    t0 = time.time()
    actor1, actor2, critic, norm1, norm2 = train_with_curriculum(cfg, K_list_curriculum, SEED)
    print(f"Training done in {time.time()-t0:.1f}s")

    print("\nRunning sweeps ...")
    res_K = sweep_vs_K_new(cfg, actor1, actor2, norm1, norm2, K_sweep)
    plot_failure_vs_K(res_K, K_sweep)
    plot_throughput(res_K, K_sweep)

    print("\nBreakdown: latency vs reliability")
    breakdown = latency_reliability_breakdown_new(cfg, actor1, actor2, norm1, norm2)
    plot_latency_reliability_breakdown(breakdown)

    radii = [20, 40, 60, 80, 100, 120]
    print("\nSweep: failure rate vs radius")
    res_r = sweep_vs_radius_new(cfg, actor1, actor2, norm1, norm2, radii)
    plot_failure_vs_radius(res_r, radii)

    p_list = [0.2, 0.5, 1.0, 1.5, 2.0, 3.0]
    print("\nSweep: failure rate vs power budget")
    res_p = sweep_vs_power_new(cfg, actor1, actor2, norm1, norm2, p_list)
    plot_power_budget_comparison(res_p, p_list)

    K_list_ct = [4, 8, 12, 16, 20, 24]
    print("\nSweep: computation time vs K")
    res_ct = compute_time_vs_K_new(cfg, actor1, actor2, norm1, norm2, K_list_ct)
    plot_computation_time(res_ct, K_list_ct)

    print("\nAll figures saved to ./figures/")
    print("=" * 78)


if __name__ == "__main__":
    main()